De json a mysql con sequelize
Innolize/renta-de-autos pull request #2
Opened 2020-11-01 09:28 UTC by Innolize

2020-11-05 03:53 UTC, fsodano commented on src/app.js
> +app.listen(8000, () => console.log('escuchando en http://localhost:8000/'))
esto estaría bueno que lo pongas desde `process.env.PORT || 8000`, es decir que te lo puedan pasar como variable de entorno

2020-11-05 03:54 UTC, fsodano commented on src/config/db.init.js
> +    // console.log("-----", test.toJSON())
Si no lo necesitás, esto que vuele.

2020-11-05 03:55 UTC, fsodano commented on src/config/di.js
> +        RentController: object(RentController).construct(get('Multer'), get('RentService'), get('CarService'), get('UserRepository')),
que el controlador use al user repository me parece raro, debería interactuar con el user service

2020-11-05 03:58 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +     * @param {import('sequelize').Sequelize} sequelizeInstance
Esto te quedó raro, me parece. En el DI lo estás pasando como parámetro y acá lo estás esperando pero al final lo importás directamente en la línea 8

2020-11-05 03:59 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +    async getData() {
getAll capaz, queda mejor. Antes llamábamos a esta función getData (en el caso de JSON) porque traía toda la data del archivo de JSON, en este caso está yendo a buscar todas las rentas

2020-11-05 04:00 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +        let id = rent.id ? rent.id : idNotDefined
```suggestion
        const id = rent.id || 0
```

2020-11-05 04:01 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +        let idNotDefined = 0
```suggestion
        const idNotDefined = 0
```

2020-11-05 04:01 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +        })
👏 💯 

sólo te pido que le pongas const

2020-11-05 04:04 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +        })
Todavía no lo vimos así que está bien, pero la lógica de negocio va en el Servicio (por ejemplo, que el usuario no pueda bookear 2 autos en las mismas fechas o que un auto no esté bookeado) y en el repositorio sólo exponés un método que se llame `getCarOrUserBookingsBetweenDates(car, user)` y entonces en el servicio decidís qué hacés.

2020-11-05 04:04 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +            throw new Error(`No se pudo crear, conflicto de fechas con renta/s de id ${ids}`)
estos errores de lógica de negocio son super importantes que tiren una excepción predefinida, onda

`BookConflictException`

2020-11-05 04:05 UTC, fsodano commented on src/module/rent/repository/rentRepository.js
> +        console.log(newRent)
👀

2020-11-05 04:06 UTC, fsodano commented on src/module/rent/view/index.html
> +
👀

2020-11-05 04:07 UTC, fsodano requested changes
muy buen laburo, faltan corregir unas cositas

2020-11-10 06:43 UTC, Innolize commented on src/module/rent/repository/rentRepository.js
> +     * @param {import('sequelize').Sequelize} sequelizeInstance
En la linea 8 estoy importando el método Op que es para hacer queries con los modelos de sequelize. Ese @param me quedó de cuando estaba probando un par de cosas... ya lo volé.

2020-11-10 06:43 UTC, Innolize commented on src/module/rent/repository/rentRepository.js
> +    async getData() {
Hecho!

2020-11-10 06:45 UTC, Innolize commented on src/module/rent/repository/rentRepository.js
> +        let idNotDefined = 0
Si bien tiene sentido esto que estoy haciendo... es como se debería hacer?
Porque por ejemplo sequelize te arranca a crear las filas de una tablas con id a partir de 1 por lo cual no puede existir uno con id 0 (a menos que yo le diga específicamente que quiero crear una  fila con id, igual aviso que no lo probé ).
 A lo sumo crear una validación a la función save que si el id es 0 no me deje? o existe algún valor default para hacer esto?

2020-11-10 06:45 UTC, Innolize commented on src/module/rent/repository/rentRepository.js
> +        })
Ahí pase todo lo que sea lógica de validación al servicio y deje solo en el repositorio lo que tenga que ver con interactuar con la base de datos. Espero a la clase que viene entonces

2020-11-10 06:46 UTC, Innolize commented on src/module/rent/repository/rentRepository.js
> +            throw new Error(`No se pudo crear, conflicto de fechas con renta/s de id ${ids}`)
Listo

2021-03-10 04:45 UTC, closed without merging